services:
  database:
    build: ./
    volumes:
      - payzo-data:/data/db

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app

  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app

volumes:
  payzo-data:
